#!/usr/bin/env bash
# The script transfers a file from our client to a server.
# Strict host key checking is disabled.
# file_path="$1"
# server_ip="$2"
# username="$3"
# ssh_key="$4"
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
