#!/usr/bin/env bash
# Install nginx
# Nginx should be listening on port 80

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello, world!" | sudo tee /var/www/html/index.html >/dev/null
sudo service nginx restart
