#!/usr/bin/env bash
#Configure a new Nginx server so that /redirect_me is redirecting to another page

# Install Nginx if not already installed
if ! command -v nginx &> /dev/null; then
    sudo apt update
    sudo apt install -y nginx
fi

REDIRECT_CONFIG="server {
    listen 80;
    listen [::]:80;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}"

# Echo the redirection configuration into a new file
echo "$REDIRECT_CONFIG" | sudo tee /etc/nginx/sites-available/redirect_me > /dev/null

# Create a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test Nginx configuration and restart Nginx
sudo nginx -t && sudo systemctl restart nginx
