#!/usr/bin/env bash
# Install nginx on your web-01 server
if command -v nginx &> /dev/null; then
	sudo apt-get -y update
	sudo apt-get -y install nginx
	echo 'Hello World!' | sudo tee /var/www/html/index.html
else
	echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
	sudo sed -i '/index index.html;/a \
    	error_page 404 /404.html;\n\
    	location = /404.html {\n\
        	internal;\n\
    	}' /etc/nginx/sites-available/default

	sudo service nginx start
fi
