#!/usr/bin/env bash
# Install nginx on your web-01 server

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo sed -i 's/listen [::]:80 default_server;/listen [::]:80;/g' /etc/nginx/sites-available/default
sudo sed -i 's/server_name _;/servername 18.233.62.29;/g' /etc/nginx/sites-available/default
sudo sed -i '/server_name 18.233.62.29;/a \
	root /var/www/html;\n\
	index index.html;\n\
	error_page 404 /404.html;\
	location = /404.html {\n\
	internal;\n\
	}' /etc/nginx/sites-available/default

sudo service nginx start
