#!/usr/bin/env bash
# Automating nginx configuration

sudo apt-get update
sudo apt-get -y install nginx

# adding the custom header
sudo sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;"
/etc/nginx/sites-available/default

sudo service nginx restart
