#!/usr/bin/env bash
# Create an RSA key pair with 4096 bits and passphrase "betty"

# Name of the private key file
PRIVATE_KEY="school"

# Number of bits in the key
BITS=4096

# Passphrase to protect the key
PASSPHRASE="betty"

# Create RSA key pair
ssh-keygen -t rsa -b $BITS -f "$PRIVATE_KEY" -N "$PASSPHRASE"
