#!/usr/bin/env bash
# Create an RSA key pair with 4096 bits and passphrase "betty"


#!/bin/bash

# Create an RSA key pair with 4096 bits and passphrase "betty"
ssh-keygen -t rsa -b 4096 -f ./school -N "betty"
